### PR TITLE
docs(readme): Improved styling of README.md

### PR DESCRIPTION
**Pull request by shivaylamba**
Issue #2 
Improving the general style of the README.md for jakapu, based around the structuring of readme files for rest of the repos. 
image

### CODE REVIEW

**Comment by shivaylamba** [comment]
@DeanJain Please review

**Comment by DeanJain** [comment]
Thanks so much for this contribution @shivaylamba ! Much Appreciated !!

**Comment by DeanJain** [comment]
Thanks so much for this contribution @shivaylamba ! Much Appreciated !!

**Comment by shivaylamba** [comment]
You are welcome! Hope to contribute more @DeanJain  :)

**Pull request merged**
